// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFood = "foods"

// Food mapped from table <foods>
type Food struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	CreateAt   time.Time `gorm:"column:create_at" json:"create_at"`
	UpdateAt   time.Time `gorm:"column:update_at" json:"update_at"`
	Name       string    `gorm:"column:name" json:"name"`
	Desc       string    `gorm:"column:desc" json:"desc"`
	Category   string    `gorm:"column:category" json:"category"`
	TimePeriod string    `gorm:"column:time_period;default:NULL" json:"time_period"`
	Image      string    `gorm:"column:image" json:"image"`
	Price      float32   `gorm:"column:price" json:"price"`
}

// TableName Food's table name
func (*Food) TableName() string {
	return TableNameFood
}
