// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderItem = "order_item"

// OrderItem mapped from table <order_item>
type OrderItem struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	OrderID  string    `gorm:"column:order_id" json:"order_id"`
	FoodID   string    `gorm:"column:food_id" json:"food_id"`
	Price    float32   `gorm:"column:price" json:"price"`
	Name     string    `gorm:"column:name" json:"name"`
	CreateAt time.Time `gorm:"column:create_at" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at" json:"update_at"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
