// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	CreateAt time.Time `gorm:"column:create_at" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at" json:"update_at"`
	UserID   string    `gorm:"column:user_id" json:"user_id"`
	Status   string    `gorm:"column:status" json:"status"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
