// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type EditUserReply struct {
	Success bool `json:"success" label:"成功"`
}

type EditUserReq struct {
	NickName string `json:"nick_name" label:"昵称"`
	Phone    string `json:"phone" label:"手机"`
	Gender   int    `json:"gender" label:"性别"`
}

type GetCurrentFoodReq struct {
	Food string `json:"food"`
}

type GetCurrentFoodReqReply struct {
	Food        string  `json:"food"   label:"食物名称"`
	Desc        string  `json:"desc"  label:"描述"`
	NearbyPrice float64 `json:"nearby_price" label:"附近的价格"`
	Image       string  `json:"image"   label:"图片"`
}

type GetFoodCategoryListReply struct {
	Item []GetFoodCategoryListReplyItem
}

type GetFoodCategoryListReplyItem struct {
	CategoryID string `json:"category_id"     label:"category_id"`
	Name       string `json:"food"   label:"食物名称"`
}

type GetFoodCategoryListReq struct {
}

type GetFoodListReq struct {
	Page     int64  // 分页页码
	PageSize int64  // 每页数量
	Category string `json:"category label:"种类"`
}

type GetFoodListReqReply struct {
	List  []GetFoodListReqReplyItem
	Total int64
}

type GetFoodListReqReplyItem struct {
	Food        string  `json:"food"   label:"食物名称"`
	Desc        string  `json:"desc"  label:"描述"`
	NearbyPrice float64 `json:"nearby_price" label:"附近的价格"`
	Image       string  `json:"image"   label:"图片"`
}

type OrderDeleteReq struct {
	OrderID string `json:"order_id" label:"订单ID"`
}

type OrderDetailReply struct {
	OrderID   string   `json:"order_id" label:"订单ID"`
	Foods     []string `json:"foods" label:"食物"`
	Remark    string   `json:"remark,omitempty" label:"备注"`
	Table     string   `json:"table,omitempty" label:"桌号"`
	Status    string   `json:"status" label:"状态"`
	CreatedAt string   `json:"created_at" label:"创建时间"`
}

type OrderListReply struct {
	Orders []OrderDetailReply `json:"orders"`
}

type OrderReply struct {
	OrderID string `json:"order" label:"order_id"`
}

type OrderReq struct {
	Foods  []string `json:"foods" label:"食物"`
	Remark string   `json:"remark,omitempty" label:"备注"`
	Table  string   `json:"table,omitempty" label:"桌号"`
}

type OrderUpdateReq struct {
	OrderID string   `json:"order_id" label:"订单ID"`
	Foods   []string `json:"foods,omitempty" label:"食物"`
	Remark  string   `json:"remark,omitempty" label:"备注"`
	Table   string   `json:"table,omitempty" label:"桌号"`
	Status  string   `json:"status,omitempty" label:"状态"`
}

type WxLoginReply struct {
	Token  string `json:"token" label:"登录成功后返回的Token"`
	UserId int64  `json:"userId" label:"用户ID"`
	IsNew  bool   `json:"isNew" label:"是否是新注册"`
}

type WxLoginReq struct {
	Code      string `json:"code" validate:"required" label:"微信临时登录Code"`
	Nickname  string `json:"nickname,optional" label:"用户昵称"`
	AvatarUrl string `json:"avatarUrl,optional" label:"头像URL"`
	Gender    int    `json:"gender,optional" label:"性别 0未知 1男 2女"`
}
