// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"menul-service/service/api/internal/middleware"
	"net/http"

	"menul-service/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.Use(middleware.Auth())
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/currnt/food",
				Handler: GetCurrentFoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/wxLogin",
				Handler: wxLoginHandler(serverCtx),
			},
		},
	)
}
