// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"menul-service/service/api/internal/middleware"
	//"menul-service/service/api/internal/middleware"
	"net/http"

	"menul-service/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 公开路由（不需要鉴权）
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/api/user/wxLogin",
			Handler: wxLoginHandler(serverCtx), // 不加中间件
		},
	})

	// 私有路由（需要鉴权）
	server.AddRoutes([]rest.Route{
		{
			Method: http.MethodGet,
			Path:   "/api/current/food",
			//Handler: GetCurrentFoodHandler(serverCtx),
			Handler: middleware.Auth()( // <- 手动包裹 handler
				GetCurrentFoodHandler(serverCtx),
			),
		},
	})
}
